import { extractSerialCandidates, sanitizeSerial } from './serial-parser.js';

const STORAGE_KEY = 'sn-scan-data-v1';
const state = { view: 'schools', selectedSchoolId: null, batch: null, ocrWorker: null, ocrLoading: false, ocrProgressHandler: null, historyQuery: '' };
const dom = { main: document.querySelector('#mainContent'), back: document.querySelector('#backButton'), headerAction: document.querySelector('#headerAction'), bottomNav: document.querySelector('#bottomNav'), modalRoot: document.querySelector('#modalRoot'), toast: document.querySelector('#toast') };
let data = loadData();
injectUpgradeStyles();

function loadData(){try{const stored=JSON.parse(localStorage.getItem(STORAGE_KEY));if(stored&&Array.isArray(stored.schools))return stored;}catch{}return{schools:[],version:2};}
function saveData(){data.version=2;localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
function uid(){return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function showToast(message){dom.toast.textContent=message;dom.toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>dom.toast.classList.remove('show'),2600);}
function selectedSchool(){return data.schools.find(s=>s.id===state.selectedSchoolId)||null;}
function allRecords(){return data.schools.flatMap(s=>(s.records||[]).map(r=>({...r,schoolId:s.id,schoolName:s.name}))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));}
function setChrome({back=false,action='add-school',nav=true}={}){dom.back.classList.toggle('hidden',!back);dom.bottomNav.classList.toggle('hidden',!nav);dom.headerAction.classList.toggle('hidden',!action);dom.headerAction.dataset.action=action||'';dom.headerAction.setAttribute('aria-label',action==='add-record'?'Add room scan':'Add school');dom.headerAction.innerHTML=action?'<svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>':'';}
function setActiveNav(view){dom.bottomNav.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));}
function render(){window.scrollTo({top:0,behavior:'instant'});switch(state.view){case'school':return renderSchool();case'room-setup':return renderRoomSetup();case'batch-scan':return renderBatchScan();case'batch-review':return renderBatchReview();case'success':return renderSuccess();case'history':return renderHistory();case'settings':return renderSettings();default:return renderSchools();}}

function renderSchools(){state.view='schools';setChrome({action:'add-school',nav:true});setActiveNav('schools');const fragment=document.querySelector('#schoolListTemplate').content.cloneNode(true);const list=fragment.querySelector('#schoolList');if(!data.schools.length)list.append(document.querySelector('#emptySchoolsTemplate').content.cloneNode(true));else[...data.schools].sort((a,b)=>a.name.localeCompare(b.name)).forEach(s=>{const row=document.querySelector('#schoolRowTemplate').content.cloneNode(true).querySelector('.school-row');const records=s.records||[];const rooms=new Set(records.map(r=>r.room));row.querySelector('strong').textContent=s.name;row.querySelector('small').textContent=`${rooms.size} ${rooms.size===1?'room':'rooms'} - ${records.length} ${records.length===1?'device':'devices'}`;row.onclick=()=>{state.selectedSchoolId=s.id;state.view='school';render();};list.append(row);});dom.main.replaceChildren(fragment);}
function renderSchool(){const school=selectedSchool();if(!school)return renderSchools();setChrome({back:true,action:'add-record',nav:true});setActiveNav('schools');const records=[...(school.records||[])].sort((a,b)=>a.room.localeCompare(b.room,undefined,{numeric:true})||new Date(a.createdAt)-new Date(b.createdAt));const rooms=new Set(records.map(r=>r.room));dom.main.innerHTML=`<section class="page"><div class="school-header"><div><h1>${esc(school.name)}</h1><p>Scan one device or a full room batch.</p></div></div><div class="stats-strip"><div class="stat"><strong>${records.length}</strong><span>Devices</span></div><div class="stat"><strong>${rooms.size}</strong><span>Rooms</span></div><div class="stat"><strong>${records.filter(r=>isToday(r.createdAt)).length}</strong><span>Today</span></div></div><button class="primary-button full-width" data-action="start-batch" type="button">Add devices to a room</button><div class="section-title"><h2>Records by room</h2>${records.length?'<button data-action="export-school" type="button">Export formatted CSV</button>':''}</div><div class="room-groups">${records.length?renderRoomGroups(records):emptyRecords()}</div><button class="fab" type="button" data-action="start-batch" aria-label="Add room scan"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg></button></section>`;}
function renderRoomGroups(records){const groups=records.reduce((m,r)=>(m.set(r.room,[...(m.get(r.room)||[]),r]),m),new Map());return[...groups.entries()].map(([room,items])=>`<section class="room-group"><div class="room-group-title"><strong>Room ${esc(room)}</strong><span>${items.length} ${items.length===1?'device':'devices'}</span></div>${items.map(recordCard).join('')}</section>`).join('');}
function recordCard(record,includeSchool=false){return`<article class="record-card"><div class="record-top"><div class="record-room">${includeSchool?`<span>${esc(record.schoolName)} - </span>`:''}Room ${esc(record.room)}</div><time class="record-date">${formatDate(record.createdAt)}</time></div><div class="serial-pair"><div class="serial-box"><span>Old S/N</span><strong>${esc(record.oldSerial)}</strong></div><svg class="serial-arrow" aria-hidden="true" viewBox="0 0 24 24"><path d="M5 12h14M14 7l5 5-5 5"/></svg><div class="serial-box"><span>New S/N</span><strong>${esc(record.newSerial)}</strong></div></div></article>`;}
function emptyRecords(){return`<div class="empty-state" style="min-height:260px;padding-top:18px"><h2>No devices yet</h2><p>Tap the plus button to scan one device or several devices for the same room.</p></div>`;}

function startBatch(){state.batch={room:'',mode:'paired',phase:'old',pendingOld:'',newSerials:[],oldSerials:[],pairs:[]};state.view='room-setup';render();}
function renderRoomSetup(){const school=selectedSchool();if(!school)return renderSchools();setChrome({back:true,action:null,nav:false});dom.main.innerHTML=`<section class="page form-page"><div class="scan-heading"><p class="step-label">Room setup</p><h1>Add one or multiple devices</h1><p>Everything in this batch will be saved under ${esc(school.name)}.</p></div><form id="roomSetupForm" class="form-card"><div class="field"><label for="roomField">Room number</label><input id="roomField" class="text-input" type="text" autocapitalize="characters" spellcheck="false" placeholder="B103" maxlength="20" required value="${esc(state.batch?.room||'')}"/></div><fieldset class="mode-picker"><legend>Choose your scanning order</legend><label class="mode-option"><input type="radio" name="mode" value="paired" ${state.batch?.mode==='paired'?'checked':''}/><span><strong>Scan each pair together</strong><small>Old S/N, then new S/N. Repeat as many times as needed.</small></span></label><label class="mode-option"><input type="radio" name="mode" value="staged" ${state.batch?.mode==='staged'?'checked':''}/><span><strong>Stage new devices first</strong><small>Scan every new S/N now. At the room, scan old S/Ns and the app pairs them in order.</small></span></label></fieldset><button class="primary-button full-width" type="submit">Start scanning</button></form></section>`;const form=dom.main.querySelector('#roomSetupForm');const field=dom.main.querySelector('#roomField');setTimeout(()=>field.focus(),80);form.onsubmit=e=>{e.preventDefault();const room=field.value.trim().toUpperCase();if(!room)return;state.batch.room=room;state.batch.mode=new FormData(form).get('mode');state.batch.phase=state.batch.mode==='staged'?'new':'old';state.view='batch-scan';render();};}
function phaseInfo(){const b=state.batch;if(b.mode==='paired')return b.phase==='old'?{title:'Scan old S/N',help:`Device ${b.pairs.length+1} for Room ${b.room}.`,button:'Use old S/N'}:{title:'Scan matching new S/N',help:`This will pair with ${b.pendingOld}.`,button:'Add device pair'};return b.phase==='new'?{title:'Scan new device S/Ns',help:`Scan all new devices for Room ${b.room}.`,button:'Add new S/N'}:{title:'Scan old device S/Ns',help:`Old device ${b.oldSerials.length+1} will pair with new device ${b.oldSerials.length+1}.`,button:'Add old S/N'};}
function renderBatchScan(){if(!state.batch)return startBatch();const info=phaseInfo();setChrome({back:true,action:null,nav:false});const fragment=document.querySelector('#scanStepTemplate').content.cloneNode(true);const page=fragment.querySelector('.scan-page');page.querySelector('.stepper').remove();page.querySelector('.step-label').textContent=`Room ${state.batch.room}`;page.querySelector('h1').textContent=info.title;page.querySelector('.step-help').textContent=info.help;page.querySelector('.continue-button').textContent=info.button;const cameraButton=page.querySelector('.camera-button'),input=page.querySelector('.camera-input'),preview=page.querySelector('.camera-preview img'),placeholder=page.querySelector('.camera-placeholder'),resultPanel=page.querySelector('.serial-result'),serialField=page.querySelector('.serial-field'),candidateList=page.querySelector('.candidate-list');const queue=document.createElement('div');queue.className='batch-queue';page.insertBefore(queue,page.querySelector('.camera-card'));renderQueue(queue);cameraButton.onclick=()=>input.click();input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const url=URL.createObjectURL(file);preview.src=url;preview.classList.remove('hidden');placeholder.classList.add('hidden');try{const candidates=await recognizeSerial(file,page);resultPanel.classList.remove('hidden');serialField.value=candidates[0]?.value||'';renderCandidateChips(candidateList,serialField,candidates.slice(1,5));serialField.focus();if(!candidates.length)showToast('No clear S/N found. Type it manually or retake.');}catch(err){console.error(err);resultPanel.classList.remove('hidden');serialField.value='';showToast('OCR could not finish. Type it manually or retake.');}finally{URL.revokeObjectURL(url);}};page.querySelector('.continue-button').onclick=()=>{const serial=sanitizeSerial(serialField.value);if(serial.length<5){showToast('Check the serial number before continuing.');serialField.focus();return;}addBatchSerial(serial);};page.querySelector('.retake-button').onclick=()=>{input.value='';preview.src='';preview.classList.add('hidden');placeholder.classList.remove('hidden');resultPanel.classList.add('hidden');input.click();};dom.main.replaceChildren(fragment);}
function renderQueue(container){const b=state.batch;let items=[],label='',doneLabel='';if(b.mode==='paired'){items=b.pairs.map((p,i)=>`${i+1}. ${p.oldSerial} -> ${p.newSerial}`);if(b.pendingOld)items.push(`${b.pairs.length+1}. ${b.pendingOld} -> waiting for new S/N`);label='Device pairs';doneLabel='Review and save room';}else if(b.phase==='new'){items=b.newSerials.map((s,i)=>`${i+1}. ${s}`);label='New S/N queue';doneLabel='Done scanning new devices';}else{items=b.oldSerials.map((s,i)=>`${i+1}. ${s} -> ${b.newSerials[i]||'unmatched'}`);label=`Old S/N queue (${b.oldSerials.length}/${b.newSerials.length})`;doneLabel='Review automatic pairs';}container.innerHTML=`<div class="batch-queue-head"><strong>${label}</strong><span>${items.length}</span></div>${items.length?`<ol>${items.map(i=>`<li>${esc(i)}</li>`).join('')}</ol>`:'<p>No serial numbers added yet.</p>'}<button class="secondary-button full-width" data-action="batch-done" type="button" ${b.mode==='paired'&&!b.pairs.length?'disabled':''}>${doneLabel}</button>`;container.querySelector('[data-action="batch-done"]').onclick=finishBatchPhase;}
function addBatchSerial(serial){const b=state.batch;if(b.mode==='paired'){if(b.phase==='old'){b.pendingOld=serial;b.phase='new';}else{b.pairs.push({oldSerial:b.pendingOld,newSerial:serial});b.pendingOld='';b.phase='old';}}else if(b.phase==='new'){b.newSerials.push(serial);}else{if(b.oldSerials.length>=b.newSerials.length){showToast('All new devices already have an old S/N.');return;}b.oldSerials.push(serial);}render();}
function finishBatchPhase(){const b=state.batch;if(b.mode==='paired'){if(b.pendingOld)return showToast('Scan the matching new S/N first.');state.view='batch-review';return render();}if(b.phase==='new'){if(!b.newSerials.length)return showToast('Scan at least one new S/N.');b.phase='old';return render();}if(b.oldSerials.length!==b.newSerials.length)return showToast(`Scan ${b.newSerials.length-b.oldSerials.length} more old S/N.`);b.pairs=b.newSerials.map((newSerial,i)=>({oldSerial:b.oldSerials[i],newSerial}));state.view='batch-review';render();}
function renderBatchReview(){const school=selectedSchool(),b=state.batch;if(!school||!b)return renderSchool();setChrome({back:true,action:null,nav:false});dom.main.innerHTML=`<section class="page form-page"><div class="scan-heading"><p class="step-label">Review room batch</p><h1>${b.pairs.length} ${b.pairs.length===1?'device':'devices'} for Room ${esc(b.room)}</h1><p>Old and new serial numbers are paired top to bottom.</p></div><div class="pair-review-list">${b.pairs.map((p,i)=>`<div class="pair-review"><span>${i+1}</span><div><small>Old S/N</small><strong>${esc(p.oldSerial)}</strong></div><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M5 12h14M14 7l5 5-5 5"/></svg><div><small>New S/N</small><strong>${esc(p.newSerial)}</strong></div></div>`).join('')}</div><div class="review-actions"><button class="primary-button" data-action="save-batch" type="button">Save all ${b.pairs.length}</button><button class="secondary-button" data-action="add-more-pairs" type="button">Add another device</button></div></section>`;}
function saveBatch(){const school=selectedSchool(),b=state.batch;if(!school||!b||!b.pairs.length)return;school.records||=[];const now=Date.now();b.pairs.forEach((p,i)=>school.records.push({id:uid(),room:b.room,oldSerial:p.oldSerial,newSerial:p.newSerial,createdAt:new Date(now+i).toISOString()}));saveData();state.view='success';render();}
function renderSuccess(){const b=state.batch;setChrome({back:false,action:null,nav:false});dom.main.innerHTML=`<section class="page form-page" style="text-align:center"><div class="success-mark"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M5 12l4 4L19 6"/></svg></div><h1>Room batch saved</h1><p style="color:var(--muted);line-height:1.55;margin-bottom:24px">Saved ${b?.pairs.length||0} ${b?.pairs.length===1?'device':'devices'} for Room ${esc(b?.room||'')}.</p><div class="review-actions"><button class="primary-button" data-action="same-room" type="button">Add more to this room</button><button class="secondary-button" data-action="another-room" type="button">Scan another room</button><button class="text-button" data-action="finish-scanning" type="button">Return to school</button></div></section>`;}

function renderHistory(){state.view='history';setChrome({action:null,nav:true});setActiveNav('history');const records=allRecords().filter(r=>`${r.schoolName} ${r.room} ${r.oldSerial} ${r.newSerial}`.toLowerCase().includes(state.historyQuery.toLowerCase()));dom.main.innerHTML=`<section class="page"><div class="page-heading"><div><h1>History</h1><p>Search every saved device replacement.</p></div></div><div class="toolbar"><input class="search-input" id="historySearch" type="search" placeholder="School, room, or S/N" value="${esc(state.historyQuery)}"/><button class="filter-button" data-action="export-all" type="button" aria-label="Export all"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 3v12M7 10l5 5 5-5M4 21h16"/></svg></button></div><div class="record-list">${records.length?records.map(r=>recordCard(r,true)).join(''):emptyRecords()}</div></section>`;const search=dom.main.querySelector('#historySearch');search.oninput=()=>{state.historyQuery=search.value;const pos=search.selectionStart;renderHistory();const next=dom.main.querySelector('#historySearch');next.focus();next.setSelectionRange(pos,pos);};}
function renderSettings(){state.view='settings';setChrome({action:'add-school',nav:true});setActiveNav('settings');dom.main.innerHTML=`<section class="page"><div class="page-heading"><div><h1>Settings</h1><p>Manage schools and back up scan data.</p></div></div><div class="settings-list"><div class="settings-card"><h2>Schools</h2><div>${data.schools.length?data.schools.map(s=>`<div class="school-manage-row"><div><strong>${esc(s.name)}</strong><br><small>${s.records?.length||0} devices</small></div><button class="mini-danger" type="button" data-delete-school="${s.id}">Delete</button></div>`).join(''):'<p>No schools created yet.</p>'}</div></div><div class="settings-card"><h2>Backup and export</h2><p>Formatted CSV exports list the school title, then each room with old and new S/N columns.</p><div class="settings-actions"><button class="secondary-button" data-action="export-all" type="button">Export all formatted CSV</button><button class="secondary-button" data-action="export-json" type="button">Download JSON backup</button><button class="secondary-button" data-action="import-json" type="button">Import JSON backup</button><input id="backupInput" class="hidden" type="file" accept="application/json,.json"/></div></div></div></section>`;}
function openSchoolModal(){dom.modalRoot.innerHTML=`<div class="modal-backdrop"><form class="modal" id="schoolModal"><h2>Create a school</h2><p>Add the school name exactly as it should appear in exports.</p><div class="field"><label for="schoolName">School name</label><input id="schoolName" class="text-input" type="text" maxlength="80" required placeholder="Greenville High School"/></div><div class="modal-actions"><button class="secondary-button" type="button" data-action="close-modal">Cancel</button><button class="primary-button" type="submit">Create school</button></div></form></div>`;const field=dom.modalRoot.querySelector('#schoolName');setTimeout(()=>field.focus(),50);dom.modalRoot.querySelector('#schoolModal').onsubmit=e=>{e.preventDefault();const name=field.value.trim();if(!name)return;if(data.schools.some(s=>s.name.toLowerCase()===name.toLowerCase()))return showToast('That school already exists.');const school={id:uid(),name,records:[]};data.schools.push(school);saveData();closeModal();state.selectedSchoolId=school.id;state.view='school';render();};}
function closeModal(){dom.modalRoot.replaceChildren();}
function deleteSchool(id){const school=data.schools.find(s=>s.id===id);if(!school)return;if(!confirm(`Delete ${school.name} and its ${school.records?.length||0} records?`))return;data.schools=data.schools.filter(s=>s.id!==id);saveData();showToast('School deleted.');renderSettings();}
function exportFormatted(records,filename){if(!records.length)return showToast('There are no records to export.');const schools=new Map();records.forEach(r=>{const name=r.schoolName||selectedSchool()?.name||'School';if(!schools.has(name))schools.set(name,[]);schools.get(name).push(r);});const rows=[];for(const[schoolName,items]of schools){rows.push([schoolName,'','']);rows.push(['Room #','Old S/N','New S/N']);items.sort((a,b)=>a.room.localeCompare(b.room,undefined,{numeric:true})||new Date(a.createdAt)-new Date(b.createdAt)).forEach(r=>rows.push([r.room,r.oldSerial,r.newSerial]));rows.push(['','','']);}const csv=rows.map(row=>row.map(cell=>`"${String(cell??'').replaceAll('"','""')}"`).join(',')).join('\r\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),filename);}
function exportSchool(){const school=selectedSchool();if(!school)return;exportFormatted((school.records||[]).map(r=>({...r,schoolName:school.name})),`${school.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-room-report.csv`);}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
function exportJson(){downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`sn-scan-backup-${new Date().toISOString().slice(0,10)}.json`);}
function importJson(file){const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!imported||!Array.isArray(imported.schools))throw new Error();data=imported;saveData();showToast('Backup imported.');renderSettings();}catch{showToast('That file is not a valid SN-Scan backup.');}};reader.readAsText(file);}
async function getOcrWorker(){if(state.ocrWorker)return state.ocrWorker;if(!window.Tesseract)throw new Error('OCR library unavailable');if(state.ocrLoading){while(state.ocrLoading)await new Promise(r=>setTimeout(r,100));return state.ocrWorker;}state.ocrLoading=true;try{const worker=await window.Tesseract.createWorker('eng',1,{logger:m=>state.ocrProgressHandler?.(m)});await worker.setParameters({tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/:.- ',preserve_interword_spaces:'1',user_defined_dpi:'300'});state.ocrWorker=worker;return worker;}finally{state.ocrLoading=false;}}
async function recognizeSerial(file,page){const panel=page.querySelector('.ocr-panel'),percent=page.querySelector('.ocr-percent'),progress=page.querySelector('.progress-track span');panel.classList.remove('hidden');const source=await enhanceImage(file);state.ocrProgressHandler=m=>{if(typeof m.progress==='number'){const v=Math.round(m.progress*100);percent.textContent=`${v}%`;progress.style.width=`${v}%`;}};try{const worker=await getOcrWorker();const result=await worker.recognize(source);return extractSerialCandidates(result.data.text);}finally{state.ocrProgressHandler=null;panel.classList.add('hidden');}}
function enhanceImage(file){return new Promise((resolve,reject)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),w=Math.max(1,Math.round(image.naturalWidth*scale)),h=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const c=canvas.getContext('2d',{willReadFrequently:true});c.drawImage(image,0,0,w,h);const p=c.getImageData(0,0,w,h),d=p.data;for(let i=0;i<d.length;i+=4){const gray=d[i]*.299+d[i+1]*.587+d[i+2]*.114,contrast=Math.max(0,Math.min(255,(gray-128)*1.55+128));d[i]=d[i+1]=d[i+2]=contrast;}c.putImageData(p,0,0);URL.revokeObjectURL(url);canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Image processing failed')),'image/jpeg',.94);};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Image could not be loaded'));};image.src=url;});}
function renderCandidateChips(container,input,candidates){container.replaceChildren();candidates.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='candidate-chip';b.textContent=c.value;b.onclick=()=>{input.value=c.value;input.focus();};container.append(b);});}
function isToday(v){return new Date(v).toDateString()===new Date().toDateString();}
function formatDate(v){const d=new Date(v);return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(d);}
function goBack(){switch(state.view){case'school':state.view='schools';break;case'room-setup':state.view='school';break;case'batch-scan':state.view='room-setup';break;case'batch-review':state.view='batch-scan';break;default:state.view='schools';}render();}
function injectUpgradeStyles(){const style=document.createElement('style');style.textContent=`.mode-picker{border:0;padding:0;margin:0;display:grid;gap:12px}.mode-picker legend{font-size:.8rem;color:#c6d3d7;font-weight:720;margin-bottom:10px}.mode-option{display:grid;grid-template-columns:24px 1fr;gap:12px;align-items:start;padding:15px;border:1px solid var(--line);border-radius:15px;background:var(--surface)}.mode-option input{width:20px;height:20px;accent-color:var(--accent)}.mode-option span{display:grid;gap:5px}.mode-option small{color:var(--muted);line-height:1.4}.batch-queue{margin-bottom:18px;padding:15px;border:1px solid var(--line);border-radius:16px;background:var(--surface)}.batch-queue-head{display:flex;justify-content:space-between;margin-bottom:10px}.batch-queue-head span{color:var(--accent);font-weight:800}.batch-queue ol{margin:0 0 14px;padding-left:22px;display:grid;gap:7px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.84rem}.batch-queue p{color:var(--muted);font-size:.84rem}.room-groups{display:grid;gap:18px}.room-group{display:grid;gap:10px}.room-group-title{display:flex;justify-content:space-between;align-items:center;padding:0 3px}.room-group-title span{color:var(--muted);font-size:.78rem}.pair-review-list{display:grid;gap:10px;margin:22px 0}.pair-review{display:grid;grid-template-columns:28px 1fr 24px 1fr;gap:9px;align-items:center;padding:13px;border:1px solid var(--line);border-radius:15px;background:var(--surface)}.pair-review>span{width:26px;height:26px;border-radius:9px;background:rgba(45,212,196,.13);color:var(--accent);display:grid;place-items:center;font-weight:800}.pair-review div{min-width:0}.pair-review small{display:block;color:var(--muted);font-size:.66rem;text-transform:uppercase}.pair-review strong{display:block;overflow-wrap:anywhere;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.82rem}.secondary-button:disabled{opacity:.4}`;document.head.append(style);}

dom.back.onclick=goBack;dom.headerAction.onclick=()=>dom.headerAction.dataset.action==='add-record'?startBatch():openSchoolModal();dom.bottomNav.onclick=e=>{const b=e.target.closest('[data-nav]');if(!b)return;state.view=b.dataset.nav;render();};dom.modalRoot.onclick=e=>{if(e.target.matches('.modal-backdrop')||e.target.closest('[data-action="close-modal"]'))closeModal();};dom.main.onclick=e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='create-school')openSchoolModal();if(action==='start-batch')startBatch();if(action==='save-batch')saveBatch();if(action==='add-more-pairs'){state.batch.phase=state.batch.mode==='staged'?'new':'old';state.view='batch-scan';render();}if(action==='same-room'){const room=state.batch.room,mode=state.batch.mode;state.batch={room,mode,phase:mode==='staged'?'new':'old',pendingOld:'',newSerials:[],oldSerials:[],pairs:[]};state.view='batch-scan';render();}if(action==='another-room')startBatch();if(action==='finish-scanning'){state.batch=null;state.view='school';render();}if(action==='export-school')exportSchool();if(action==='export-all')exportFormatted(allRecords(),'sn-scan-all-schools-room-report.csv');if(action==='export-json')exportJson();if(action==='import-json')dom.main.querySelector('#backupInput')?.click();const del=e.target.closest('[data-delete-school]');if(del)deleteSchool(del.dataset.deleteSchool);};dom.main.onchange=e=>{if(e.target.id==='backupInput'&&e.target.files?.[0])importJson(e.target.files[0]);};window.addEventListener('beforeunload',()=>state.ocrWorker?.terminate?.());render();